version: "3.9"

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://root:rootpassword@localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      - mongodb_container
    develop:
      watch:
        - action: rebuild
          path: ./backend/

volumes:
  mongodb_data_container:
